# Generated by Django 2.1.dev20180215012401 on 2018-04-23 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Product'),
        ),
        migrations.AlterField(
            model_name='facture',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.User'),
        ),
        migrations.AlterField(
            model_name='panier',
            name='qte',
            field=models.IntegerField(),
        ),
    ]
