# Generated by Django 2.1.dev20180215012401 on 2018-05-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20180423_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='orders',
            field=models.IntegerField(default=0),
        ),
    ]
