# Generated by Django 2.1.dev20180215012401 on 2018-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.ImageField(default='image/no_image_available.jpg', upload_to='image_folder/'),
        ),
    ]
