# Generated by Django 2.1.dev20180215012401 on 2018-05-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_marque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='logo',
            field=models.ImageField(default='static /images/marques/no_image_available.jpg', upload_to='static /images/marques/'),
        ),
    ]
