# Generated by Django 2.1.dev20180215012401 on 2018-05-10 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20180510_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='logo',
            field=models.ImageField(default='marques/no_image_available.jpg', upload_to='marques/'),
        ),
    ]
