# Generated by Django 2.1.dev20180215012401 on 2018-05-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20180510_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marque',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
