# Generated by Django 2.1.dev20180215012401 on 2018-05-12 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
