# Generated by Django 2.1.dev20180215012401 on 2018-05-13 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_delete_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='prod',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.Product'),
        ),
    ]
